---
# --config-from option is not available
# https://docs.ansible.com/ansible/latest/modules/docker_network_module.html
- name: Create macvlan network configs
  become: True
  shell: docker network create -d macvlan --scope swarm --attachable --config-from mvl_pihole_config mvl_pihole
