---
# docker_network does not support --config-only
- name: Create macvlan network configs
  become: True
  shell: docker network create -d null --config-only --opt parent=eth0 --subnet 192.168.1.0/24 --gateway 192.168.1.1 --ip-range {{ pihole_ip }}/32 mvl_pihole_config
