---
- name: Add GlusterFS apt key
  become: yes
  apt_key:
    url: https://download.gluster.org/pub/gluster/glusterfs/7/rsa.pub
    state: present

# debian stuck on version 5, add backports
- name: Add backports key
  become: True
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: '{{ item }}'
  loop:
    - 04EE7237B7D453EC
    - 648ACFD622F3D138
  when: ansible_facts['distribution'] is match("Debian")

- name: Add buster backports
  become: True
  apt_repository:
    repo: deb https://deb.debian.org/debian buster-backports main
    state: present
  when: ansible_facts['distribution'] is match("Debian")

- name: Install rpcbind
  become: True
  apt:
    pkg:
      - rpcbind
    state: latest
    update_cache: yes

- name: Install GlusterFS
  become: True
  apt:
    pkg:
      - glusterfs-server
    default_release: "{{ ansible_facts['distribution'] is match('Debian') | ternary('buster-backports', omit) }}"
    state: latest
    update_cache: yes

- name: Start GlusterFS arm
  become: True
  systemd:
    name: '{{ item }}'
    enabled: yes
    state: started
  loop:
    - glusterd
    - glustereventsd
  when: ansible_facts['architecture'] is match("arm.*")

# NanoPi not liking service or systemd modules
- name: Start GlusterFS aarch
  become: True
  command: systemctl enable '{{ item }}' && systemctl start '{{ item }}'
  loop:
    - glusterd
    - glustereventsd
  when: ansible_facts['architecture'] is match("aarch.*")

- name: Create GlusterFS directories
  become: True
  file:
    path: '/mnt/glusterfs/{{ item.dir }}'
    state: directory
  loop:
    - { dir: bricks }
    - { dir: vol }
