---
version: "3.7"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    image: pihole/pihole:latest
    networks:
      - dns
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    environment:
      TZ: 'America/Los_Angeles'
      #WEBPASSWORD: ''
      IPv6: 'false'
      CONDITIONAL_FORWARDING: 'true'
      CONDITIONAL_FORWARDING_IP: '192.168.1.1'
      CONDITIONAL_FORWARDING_DOMAIN: 'local'
      DNSMASQ_LISTENING: 'local'
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
    volumes:
       - /mnt/glusterfs/vol/pihole/etc-pihole:/etc/pihole/
       - /mnt/glusterfs/vol/pihole/etc-dnsmasq.d:/etc/dnsmasq.d/
       - /mnt/glusterfs/vol/pihole/resolv.conf:/etc/resolv.conf
    dns:
      - 127.0.0.1
    deploy:
       mode: replicated
       replicas: 2
       placement:
          constraints:
             - "node.labels.dns==true"
networks:
  dns:
    external:
      name: mvl_pihole
